---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentry.name" . }}
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sentry.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
